namespace OpenMetrc.Builder.Models;

public class PackageLabTest
{
    public string? LabFacilityLicenseNumber { get; set; }
    public string? LabFacilityName { get; set; }
    public bool? OverallPassed { get; set; }
    public DateOnly? TestPerformedDate { get; set; }
    public bool? ResultReleased { get; set; }
    public DateTime? ResultReleaseDateTime { get; set; }
    public string? TestTypeName { get; set; }
    public bool? TestPassed { get; set; }
    public decimal TestResultLevel { get; set; }
    public string? TestComment { get; set; }
    public bool? TestInformationalOnly { get; set; }
    public long Id { get; set; }
    public string? Label { get; set; }
    public string? PackageType { get; set; }
    public int? SourceHarvestCount { get; set; }
    public int? SourcePackageCount { get; set; }
    public int? SourceProcessingJobCount { get; set; }
    public string? SourceHarvestNames { get; set; }
    public string? SourcePackageLabels { get; set; }
    public long? LocationId { get; set; }
    public string? LocationName { get; set; }
    public string? LocationTypeName { get; set; }
    public decimal? Quantity { get; set; }
    public string? UnitOfMeasureName { get; set; }
    public string? UnitOfMeasureAbbreviation { get; set; }
    public string? PatientLicenseNumber { get; set; }
    public string? ItemFromFacilityLicenseNumber { get; set; }
    public string? ItemFromFacilityName { get; set; }
    public string? Note { get; set; }
    public DateOnly? PackagedDate { get; set; }
    public DateOnly? ExpirationDate { get; set; }
    public DateOnly? SellByDate { get; set; }
    public DateOnly? UseByDate { get; set; }
    public string? InitialLabTestingState { get; set; }
    public string? LabTestingState { get; set; }
    public DateOnly? LabTestingStateDate { get; set; }
    public DateOnly? LabTestingRecordedDate { get; set; }
    public bool? IsProductionBatch { get; set; }
    public string? ProductionBatchNumber { get; set; }
    public string? SourceProductionBatchNumbers { get; set; }
    public bool? IsTradeSample { get; set; }
    public bool? IsTradeSamplePersistent { get; set; }
    public bool? SourcePackageIsTradeSample { get; set; }
    public bool? IsDonation { get; set; }
    public bool? IsDonationPersistent { get; set; }
    public bool? SourcePackageIsDonation { get; set; }
    public bool? IsTestingSample { get; set; }
    public bool? IsProcessValidationTestingSample { get; set; }
    public bool? ProductRequiresRemediation { get; set; }
    public bool? ContainsRemediatedProduct { get; set; }
    public DateOnly? RemediationDate { get; set; }
    public DateTime? ReceivedDateTime { get; set; }
    public string? ReceivedFromManifestNumber { get; set; }
    public string? ReceivedFromFacilityLicenseNumber { get; set; }
    public string? ReceivedFromFacilityName { get; set; }
    public bool? IsOnHold { get; set; }
    public DateOnly? ArchivedDate { get; set; }
    public DateOnly? FinishedDate { get; set; }
    public bool? IsOnTrip { get; set; }
    public bool? IsOnRetailerDelivery { get; set; }
    public string? PackageForProductDestruction { get; set; }
    public DateTime? LastModified { get; set; }
    public PackageLabTestItem? Item { get; set; }
}