global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Annotations;
global using OpenMetrc.Builder.Domain.Requests;
global using System.ComponentModel.DataAnnotations;
global using OpenMetrc.Builder.Common.Attributes;
global using OpenMetrc.Builder.Common.Data;
global using OpenMetrc.Builder.Common.Filters;
global using OpenMetrc.Builder.Domain;